version: "3.4"

services:
  # postgres:
  #   container_name: postgres
  #   image: "postgres:${POSTGRES_TAG}"
  #   restart: unless-stopped
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - postgres:/var/lib/postgresql/data/pgdata
  #   networks:
  #     - oxygen_django
  #   environment:
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_NAME}
  #     - POSTGRES_USER=${DB_USER}
  #     - PGDATA=/var/lib/postgresql/data/pgdata
  #     - PGUSER=${DB_USER}
  #   healthcheck:
  #           test: ["CMD-SHELL", "pg_isready"]
  #           timeout: 20s
  #           retries: 10
  oxygen_django:
    container_name: oxygen_django
    image: oxygen_django:latest
    restart: unless-stopped
    # depends_on:
    #   postgres:
    #       condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - oxygen_django:/app
      - ./.env:/app/.env:ro
    networks:
      - oxygen_django
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
volumes:
  oxygen_django:
  postgres:
networks:
  oxygen_django:
